[package]
name = "coding_assignment"
version = "0.1.0"
authors = ["Jan van Brügge <supermanitu@gmail.com>"]

[dependencies]
vulkano = "0.10"
vulkano-shader-derive = "0.10.0"
vulkano-win = "0.10"
winit = "0.17"
